<?php
require_once  '/wamp/www/vmas/includes/path.php';
 //$db->access_drop_table(false);

// assume I am logged in as admin
// when user login is functioning this will be generated by the session
$security = 0;
//$session->logout();
$user = User::get_user_by_id(1); // this will change based on which user is logged in as of right now it is hard coded as 1
$session->login(attempt_login($user->username, "8F2017-farms", $user), $user->security);
$session->is_logged_in($user->security);
$admin = $session->is_master();
//var_dump($session->is_logged_in($user->security));
$menu = Menu::find_menu_by_user_security($user->security);
$submenus = Submenu::find_submenu_by_menu_id($menu->id);

?>
		<?php include_layout_template('vmas_header.php')?>
		<div class="row">
			<div class="large-12 medium-12 small-12 columns">
				<h1 class="text-center"><strong>V</strong>echicle <strong>M</strong>aintenance <strong>A</strong>nd <strong>S</strong>ervice<br/>Log</h1>
				<div class="text-center">
					DEBUG CODE:<br/>
					<?php echo JS_PATH;?>
				</div>
			</div>
		</div>

<!-- MENU -->
<div class="row">
	<div class="large-12 medium-12 small-12 columns">
		<div class="title-bar" data-responsive-toggle="main-menu" data-hide-for="large">
  			<button class="menu-icon" type="button" data-toggle></button>
			<div class="title-bar-title">&nbsp;&nbsp;Menu</div>
		</div>
		<div class="top-bar" id="main-menu">
			<div class="top-bar-left">
				<ul class="dropdown menu" data-dropdown-menu>
					<li class="menu-text">Site Title</li>
				</ul>
			</div>
			<div class="top-bar-left">
				<ul class="menu" data-responsive-menu="drilldown medium-dropdown">
					<li class="has-submenu"><a href="#">Twenty</a>
						<ul class="submenu menu vertical" data-submenu>
							<li><a href="#">One</a></li>
							<li><a href="#">Two</a>
								<ul class="submenu menu vertical" data-submenu>
									<li><a href="#">Millenials</a></li>
									<li><a href="#">Generationals</a></li>
									<li><a href="#">Baby Boomers</a></li>
									<li><a href="#">Gen X'ers</a></li>
								</ul>
							</li>
							<li><a href="#">Three</a></li>
							<li><a href="#">Four</a></li>
						</ul>
					</li>
				</ul>
			</div>
			<div class="top-bar-right">
				<ul class="menu" data-responsive-menu="drilldown medium-dropdown">
					<li class="has-submenu"><a href="#">One</a>
						<ul class="submenu menu vertical" data-submenu>
							<li><a href="#">Old</a>
								<ul class="submenu menu vertical" data-submenu>
									<li><a href="#">Extreme Historic</a></li>
									<li><a href="#">Historic</a></li>
									<li><a href="#">Restorable</a></li>
								</ul>
							</li>
							<li><a href="#">New</a></li>
							<li><a href="#">Used</a></li>
						</ul>
					</li>
					<li><a href="#">Two</a></li>
					<li><a href="#">Three</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<?php new_row_foundation();?>
	<?php full_screen_foundation(3, 3, 2); ?>
		&nbsp;
	<?php end_single_foundation(); ?>
	<?php full_screen_foundation(6, 6, 8); ?>
		<?php echo output_errors($session->errors); ?>
		<?php echo output_message($session->message); ?>
	<?php end_single_foundation(); ?>
	<?php full_screen_foundation(3, 3, 2)?>
		&nbsp;
<?php end_screen_foundation(); ?>
<?php new_row_foundation(); full_screen_foundation(3,3,2); ?>
		&nbsp;
<?php end_single_foundation(); ?>
	<?php full_screen_foundation(6, 6, 8); ?>
		<div class="text-center">
			<?php // drop, menu, submenu, subsubmenu, master are all that is available at this time. Check database.php->secure_access?>
			<?php // array('drop', 'menu', 'submenu', 'subsubmenu', 'master') ?>
			<?php $db->secure_access()?>
	<?php end_screen_foundation(); ?>
	<div class="large-3 medium-3 small-2 columns">
		&nbsp;
<?php end_screen_foundation(); ?>
<?php include_layout_template('vmas_footer.php'); ?>

<?php 

function call_it() {
	?>
	<?php foreach ($submenus as $drop_menu) { ?>
								<?php $subsubmenu = Subsubmenu::get_subsubmenu($drop_menu->id, $session->find_clearance()); ?>
									<?php if ((!$drop_menu->admin) || $admin) { // only show if the Admin user?>
										<?php // if user clearance is 99 they have lowest clearance level and only logout will show ?>
										<?php if ($session->find_clearance()) { ?> 
											<li><a href="<?php echo $drop_menu->url; ?>" style="font-size: .83em;" class="button"><?php echo $drop_menu->link_text; ?></a>
											<?php if ($subsubmenu) { ?>
												<ul class="menu vertical">
												<?php foreach ($subsubmenu as $nextmenu) { ?>
													<?php if ((!$nextmenu->admin) || ($admin)) { // only show if the Admin user?>
														<li><a href="<?php echo $nextmenu->url; ?>" style="font-size: .95em;"><?php echo $nextmenu->link_text; ?></a></li>
													<?php } ?>
												<?php } ?>
												</ul>
											<?php } ?>
											</li>
										<?php } else { ?>
											<li><a href="<?php echo $drop_menu->url; ?>" style="font-size: .83em;" class="button"><?php echo $drop_menu->link_text; ?></a>
												<?php if ($subsubmenu) { ?>
													<ul class="menu vertical">
														<?php foreach ($subsubmenu as $nextmenu) { ?>
															<?php if ($nextmenu->admin == 0 || ($admin)) { ?>
																<li style="font-size: .95em;"><a href="<?php echo $nextmenu->url; ?>"><?php echo $nextmenu->link_text; ?></a></li>
															<?php } ?>
														<?php } ?>
													</ul>
												<?php } ?>
											</li>
										<?php } ?>
									<?php } ?>
								<?php } ?>
							</ul>
						</div>
					</div>	
		<?php 
}
?>
